"use client";

import { useState, useRef, useCallback } from "react";
import { TemplateId, TEMPLATES } from "@/lib/templates";
import styles from "./ResultPanel.module.css";

interface ResultPanelProps {
  title: string;
  content: string;
  templateId: TemplateId;
  onRegenerate: () => void;
}

export default function ResultPanel({
  title,
  content,
  templateId,
  onRegenerate,
}: ResultPanelProps) {
  const [editableContent, setEditableContent] = useState(content);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const contentRef = useRef<HTMLTextAreaElement>(null);
  const template = TEMPLATES[templateId];

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(editableContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for browsers without clipboard API
      if (contentRef.current) {
        contentRef.current.select();
        document.execCommand("copy");
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    }
  }, [editableContent]);

  const handleDownloadMarkdown = useCallback(() => {
    const safeName = title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
    const filename = `studysnap_${safeName}.md`;
    const fullContent = `# ${title}\n\n${editableContent}`;
    const blob = new Blob([fullContent], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }, [title, editableContent]);

  const handleDownloadPDF = useCallback(async () => {
    setDownloading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(80, 0, 200);
      doc.text(title, margin, 25);

      // Template label
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(120, 100, 160);
      doc.text(`${template.icon} ${template.label} · Generated by StudySnap`, margin, 33);

      // Divider
      doc.setDrawColor(200, 180, 230);
      doc.line(margin, 37, pageWidth - margin, 37);

      // Content (strip markdown syntax for PDF)
      const plainText = editableContent
        .replace(/#{1,6}\s/g, "")
        .replace(/\*\*(.*?)\*\*/g, "$1")
        .replace(/\*(.*?)\*/g, "$1")
        .replace(/`(.*?)`/g, "$1")
        .replace(/^\s*[-*+]\s/gm, "• ")
        .replace(/^\s*\d+\.\s/gm, "")
        .replace(/\|.*\|/g, "") // tables
        .replace(/^---+$/gm, "")
        .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(30, 20, 50);

      const lines = doc.splitTextToSize(plainText, maxWidth);
      let y = 45;
      const lineHeight = 6;
      const pageHeight = doc.internal.pageSize.getHeight();

      for (const line of lines) {
        if (y + lineHeight > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
        // Bold headings
        if (line.match(/^(📌|✅|🔑|📋|🎯|🃏|🧠|💬|#|##)/)) {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(80, 0, 200);
        } else {
          doc.setFont("helvetica", "normal");
          doc.setTextColor(30, 20, 50);
        }
        doc.text(line, margin, y);
        y += lineHeight;
      }

      // Footer
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8);
      doc.setTextColor(160, 140, 180);
      doc.text(
        "Generated by StudySnap · studysnap.app",
        margin,
        pageHeight - 10
      );

      const safeName = title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
      doc.save(`studysnap_${safeName}.pdf`);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setDownloading(false);
    }
  }, [title, editableContent, template]);

  return (
    <div className={`card ${styles.result} animate-fade-in`}>
      {/* Header */}
      <div className={styles.header}>
        <div className={styles.headerLeft}>
          <span className={styles.templateIcon}>{template.icon}</span>
          <div>
            <div className={styles.templateLabel}>{template.label}</div>
            <h2 className={styles.title}>{title}</h2>
          </div>
        </div>
        <button
          className={`btn btn-secondary ${styles.regenBtn}`}
          onClick={onRegenerate}
          id="regenerate-button"
        >
          🔄 Regenerate
        </button>
      </div>

      {/* Edit hint */}
      <div className={styles.editHint}>
        ✏️ You can edit the output below before copying or downloading.
      </div>

      {/* Editable content */}
      <textarea
        ref={contentRef}
        className={`textarea ${styles.contentArea}`}
        value={editableContent}
        onChange={(e) => setEditableContent(e.target.value)}
        rows={24}
        spellCheck
        aria-label="Generated study materials (editable)"
      />

      {/* Export buttons */}
      <div className={styles.exportBar}>
        <div className={styles.exportLeft}>
          <button
            className={`btn ${copied ? "btn-success" : "btn-ghost"}`}
            onClick={handleCopy}
            id="copy-button"
          >
            {copied ? "✅ Copied!" : "📋 Copy to clipboard"}
          </button>
          <button
            className="btn btn-ghost"
            onClick={handleDownloadMarkdown}
            id="download-md-button"
          >
            ⬇️ Download .md
          </button>
          <button
            className="btn btn-ghost"
            onClick={handleDownloadPDF}
            disabled={downloading}
            id="download-pdf-button"
          >
            {downloading ? "⏳ Generating PDF..." : "📄 Export PDF"}
          </button>
        </div>
        <span className={styles.charCount}>
          {editableContent.length.toLocaleString()} chars
        </span>
      </div>
    </div>
  );
}
